title: Lascia Corre Distribution
description: Votre distributeur en Corse du Sud
logo: "/assets/LCD logo.jpg"
theme: just-the-docs

url: https://juanitito.github.io/LCD/

aux_links:
  Retour: https://juanitito.github.io/LCD/
