title: Lascia Corre Distribution
description: Votre distributeur en Corse du Sud
theme: just-the-docs
logo: "/assets/LCD logo.jpg"
url: https://juanitito.github.io/LCD/

aux_links:
  Retour: https://juanitito.github.io/LCD/
