title: Lascia Corre Distribution
description: Votre distributeur en Corse du Sud
theme: just-the-docs

url: https://juanitito.github.io/LCD/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
